# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1de132c05efead9457e9b434f503cd6716e36f1914f6396359f40b28fca500ac7a994711c5befb7951fdc337cfe451086814e2836edb313bd92579f56e6290d7

test:
  secret_key_base: c798a384e4435dfe9a07be749a1cce9629cc5cbe5e881f7d96b42e4803f71bbba7664807ee2a79bc005a644f2c2b56826d99553b32957b33cb5b2da4bb869a4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
